<a href="https://colab.research.google.com/github/shubhmittal-627/ShubhMittal-Cognitive-Computing-UCS420-/blob/main/assignment(6).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ques1(a)

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
temp_adjusted = temperature + 2


ques1(b)

In [2]:
temp_fahrenheit = (9 / 5) * temperature + 32


ques1(c)

In [ ]:
readings_gt_32 = temperature[temperature > 32]


ques1(d)

In [ ]:
count_gt_32 = np.sum(temperature > 32)


ques2(a)

In [4]:
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
total_steps = np.sum(steps)


ques2(b)

In [5]:
mean_steps = np.mean(steps)


ques2(c)

In [6]:
max_steps = np.max(steps)
min_steps = np.min(steps)

ques2(d)

In [7]:
daily_totals = np.sum(steps, axis=0)

ques 3

In [8]:
import numpy as np

# --- a
original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original array:", original)

# --- b.
subset = original[1:4]
print("b. Subset array:", subset)

# --- c.
subset[0] = 999
print("c. Modified subset:", subset)
print("   Original after subset modification:", original)

original = np.array([1, 2, 3, 4, 5, 6])

# --- d.
subset_copy = original[1:4].copy()
subset_copy[0] = 500
print("d. Modified copied subset:", subset_copy)
print("   Original after copy modification:", original)

# --- e.
matrix = np.arange(1, 13).reshape(3, 4)
print("\ne. 3x4 Matrix:\n", matrix)

# --- f.
print("\nf. Slicing operations:")
print("   • First row:", matrix[0, :])
print("   • Last row:", matrix[-1, :])
print("   • Second column:", matrix[:, 1])
print("   • Rows 1-2 and Columns 2-3:\n", matrix[1:3, 2:4])

# --- g.
flat_arr = matrix.flatten()
ravel_arr = matrix.ravel()
print("\ng. matrix.flatten():", flat_arr)
print("   matrix.ravel():  ", ravel_arr)

# --- h.
ravel_arr[0] = 777
print("\nh. Modified ravel()[0] to 777.")
print("   Original matrix affected?: YES\n", matrix)

# --- i.
flat_arr[1] = 888
print("\ni. Modified flatten()[1] to 888.")
print("   Original matrix affected?: NO\n", matrix)

# --- j.
print("\nj. Matrix attributes:")
print("   • shape:", matrix.shape)
print("   • ndim: ", matrix.ndim)
print("   • size: ", matrix.size)
print("   • dtype:", matrix.dtype)

a. Original array: [1 2 3 4 5 6]
b. Subset array: [2 3 4]
c. Modified subset: [999   3   4]
   Original after subset modification: [  1 999   3   4   5   6]
d. Modified copied subset: [500   3   4]
   Original after copy modification: [1 2 3 4 5 6]

e. 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

f. Slicing operations:
   • First row: [1 2 3 4]
   • Last row: [ 9 10 11 12]
   • Second column: [ 2  6 10]
   • Rows 1-2 and Columns 2-3:
 [[ 7  8]
 [11 12]]

g. matrix.flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
   matrix.ravel():   [ 1  2  3  4  5  6  7  8  9 10 11 12]

h. Modified ravel()[0] to 777.
   Original matrix affected?: YES
 [[777   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

i. Modified flatten()[1] to 888.
   Original matrix affected?: NO
 [[777   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

j. Matrix attributes:
   • shape: (3, 4)
   • ndim:  2
   • size:  12
   • dtype: int64


ques4

In [9]:
import numpy as np

y = np.array([40, 65, 30, 85])
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

# a.
shape_X = X.shape
ndim_X = X.ndim

# b.
X_T = X.T

# c.
XTX = X_T @ X

# d.
XTX_inv = np.linalg.inv(XTX)

# e.
beta = XTX_inv @ X_T @ y

# g.
new_user = np.array([5, 40, 7])
pred_score = new_user @ beta


print(f"a. Shape of X: {shape_X}, Dimensions of X: {ndim_X}\n")
print("b. Transpose of X (X.T):\n", X_T, "\n")
print("c. Matrix Product (X.T @ X):\n", XTX, "\n")
print("d. Inverse of (X.T @ X):\n", XTX_inv, "\n")
print("e. Calculated Coefficients (Beta):\n", beta, "\n")
print(f"g. Predicted Assistance Score for new user: {pred_score:.2f}")

a. Shape of X: (4, 3), Dimensions of X: 2

b. Transpose of X (X.T):
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]] 

c. Matrix Product (X.T @ X):
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]] 

d. Inverse of (X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]] 

e. Calculated Coefficients (Beta):
 [-0.15921454  0.14083853 10.06302242] 

g. Predicted Assistance Score for new user: 75.28
