<a href="https://colab.research.google.com/github/shubhmittal-627/ShubhMittal-Cognitive-Computing-UCS420-/blob/main/assignment(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ques1

In [1]:
import numpy as np


arr = np.array([10, 20, 30, 40, 50])

# a)
add_2 = arr + 2

# b)
mult_3 = arr * 3

# c)
div_2 = arr / 2

print("a) Add 2:", add_2)
print("b) Multiply 3:", mult_3)
print("c) Divide 2:", div_2)

a) Add 2: [12 22 32 42 52]
b) Multiply 3: [ 30  60  90 120 150]
c) Divide 2: [ 5. 10. 15. 20. 25.]


ques2

In [ ]:
#(a)
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed:", reversed_arr)
#(b)
# i. Array x
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
vals_x, counts_x = np.unique(x, return_counts=True)
most_freq_x = vals_x[np.argmax(counts_x)]
indices_x = np.where(x == most_freq_x)[0]

print("x -> Most Frequent Value:", most_freq_x)
print("x -> Indices:", indices_x)

# ii. Array y
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals_y, counts_y = np.unique(y, return_counts=True)
max_count_y = np.max(counts_y)
most_freq_y = vals_y[counts_y == max_count_y]
indices_y = {val: np.where(y == val)[0] for val in most_freq_y}

print("y -> Most Frequent Value(s):", most_freq_y)
for val, idx in indices_y.items():
  print(f"y -> Indices for value {val}:", idx)

ques3

In [2]:

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a)
elem_a = arr[0, 1]

# b)
elem_b = arr[2, 0]

print("a) 1st row, 2nd column:", elem_a)
print("b) 3rd row, 1st column:", elem_b)

a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


ques4

In [3]:
import numpy as np

student_name = np.linspace(10, 100, 25)


print("Dimensions (ndim):", student_name.ndim)  # Output: 1
print("Shape:", student_name.shape)  # Output: (25,)
print("Total Elements (size):", student_name.size)  # Output: 25
print("Data Type (dtype):", student_name.dtype)  # Output: float64
print(
    "Total Bytes Consumed (nbytes):", student_name.nbytes
)


transpose_reshape = student_name.reshape(25, 1)
print("\nTransposed via reshape(25, 1):\n", transpose_reshape)

Dimensions (ndim): 1
Shape: (25,)
Total Elements (size): 25
Data Type (dtype): float64
Total Bytes Consumed (nbytes): 200

Transposed via reshape(25, 1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


ques5

In [4]:
import numpy as np

ucs420_student_name = np.array(
    [[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]]
)


mean_val = np.mean(ucs420_student_name)
median_val = np.median(ucs420_student_name)
max_val = np.max(ucs420_student_name)
min_val = np.min(ucs420_student_name)
unique_elems = np.unique(ucs420_student_name)

print("Mean:", mean_val)
print("Median:", median_val)
print("Max:", max_val)
print("Min:", min_val)
print("Unique Elements:", unique_elems)


reshaped_ucs420_student_name = ucs420_student_name.reshape(4, 3)
print("\nReshaped (4x3):\n", reshaped_ucs420_student_name)


resized_ucs420_student_name = np.resize(ucs420_student_name, (2, 3))
print("\nResized (2x3):\n", resized_ucs420_student_name)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3):
 [[10 20 30]
 [40 50 60]]
